# Generated by Django 5.0.4 on 2024-04-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_listing',
            name='old_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
